getwd()
setwd("/Users/karenwang/Documents/Mirror of Identity")

library("dplyr")
library("car")
library("stargazer")
library("corrplot")
library("backports")     # to revive the isFALSE() function for sim_slopes()
library("effects")       # for probing interactions
library("ggplot2")       # for data visualization
library("interactions")  # for probing/plotting interactions
library("lme4")          # for multilevel models
library("lmerTest")      # for p-values
library("psych")         # for describing the data
library("plyr")          # for data manipulation
library("Hmisc")
library("lavaan")
library("semPlot")
library("tidyverse")
library("optimx")

# Import and fill NAs
data <- read.csv("EMA_Daten_Final.csv", header=TRUE)
data[data==888] <- NA

# Reverse code SA1 and RA1
data$SA_1 <- 6-data$SA_1
data$RA_1 <- 6-data$RA_1

# Simplify German Column Names
names(data)[names(data) == "Befragung"] <- "Prompt_Num"

# Create H1 data set
full_cols = c("ID",
              "Prompt_Num",
              "Beep",
              "SA_1","SA_2",
              "RA_1","RA_2",
              "PB_1","PB_2",
              "TB_1","TB_2")

data_h1 <- data[,full_cols]

# Compute simple latent variables
data_h1$PB = rowMeans(data_h1[,c("PB_1","PB_2")])
data_h1$TB = rowMeans(data_h1[,c("TB_1","TB_2")])
data_h1$SA = rowMeans(data_h1[,c("SA_1","SA_2")])
data_h1$RA = rowMeans(data_h1[,c("RA_1","RA_2")])

# Descriptive stats
cols = c(
         "SA_1","SA_2","SA",
         "RA_1","RA_2","RA",
         "PB_1","PB_2","PB",
         "TB_1","TB_2","TB"
         )

# Compute n,means,sd,min,max
col_n <- data_h1   %>%
  select(cols) %>%
  {colSums(is.na(.)==FALSE)} 

col_mean <- data_h1   %>% 
  dplyr::summarize(across(cols,mean,na.rm=TRUE))

col_sd <- data_h1   %>% 
  dplyr::summarize(across(cols,sd,na.rm=TRUE))

col_min <- data_h1   %>% 
  dplyr::summarize(across(cols,min,na.rm=TRUE))

col_max <- data_h1   %>% 
  dplyr::summarize(across(cols,max,na.rm=TRUE))

stats <- cbind("n"=as.vector(col_n),
               "mean"=as.vector(col_mean),
               "sd"=as.vector(col_sd),
               "min"=as.vector(col_min),
               "max"=as.vector(col_max))
stats

vars <- c("SA","RA","PB","TB")
# Correlation Matrix
rcorr_result <- rcorr(as.matrix(na.omit(data_h1[, vars])), type="spearman")
rcorr_matrix <- rcorr_result$r
rcorr_matrix
corrplot(rcorr_matrix, 
         method = "color", 
         type = "lower", 
         order = "original",
         tl.col = "black", # Text label color
         tl.srt = 360, # Text label rotation
         diag = FALSE) # Exclude the diagonal

# Aggregate entries to person level
vars2 = c("ID",vars)
data_person <- aggregate(. ~ ID, data = data_h1[,vars2], mean)

# Correlation matrix of all entries
pairs.panels(data_h1[,vars], main="Correlation Matrix of All Entries")
# Correlation matrix of person means
pairs.panels(data_person[,vars], main="Correlation Matrix of Person Means")

# Adding n-1 to dataset
data_h1 <- data_h1 %>% 
  group_by(ID) %>% 
  mutate(SA_lag = lag(SA),
         RA_lag = lag(RA),
         PB_lag = lag(PB),
         TB_lag = lag(TB))

# Add label of first daily prompts
data_h1 <- data_h1 %>%
  mutate(
    First_Prompt_of_Day = ifelse(Beep == 1, 1, 0)) 

# Appending person means to data
data_h1 <- merge(data_h1,data_person,by="ID",suffix = c("", "_mean"))

# Center the variables around person means
data_h1$SA_mean_c <- scale(data_h1$SA_mean,center=TRUE,scale=FALSE)
data_h1$RA_mean_c <- scale(data_h1$RA_mean,center=TRUE,scale=FALSE)
data_h1$PB_mean_c <- scale(data_h1$PB_mean,center=TRUE,scale=FALSE)
data_h1$TB_mean_c <- scale(data_h1$TB_mean,center=TRUE,scale=FALSE)

data_h1$SA_c <- data_h1$SA - data_h1$SA_mean
data_h1$RA_c <- data_h1$RA - data_h1$RA_mean
data_h1$PB_c <- data_h1$PB - data_h1$PB_mean
data_h1$TB_c <- data_h1$TB - data_h1$TB_mean

data_h1$SA_lag_c <- data_h1$SA_lag - data_h1$SA_mean
data_h1$RA_lag_c <- data_h1$RA_lag - data_h1$RA_mean
data_h1$PB_lag_c <- data_h1$PB_lag - data_h1$PB_mean
data_h1$TB_lag_c <- data_h1$TB_lag - data_h1$TB_mean

# MODEL 1: SA/RA/TB ->PB
## MODEL NULL - ICC
m0_pb <- lmer(formula = PB ~ 1 + (1|ID), 
              data=data_h1,
              na.action=na.exclude)
summary(m0_pb)
rf_pb <- as.data.frame(VarCorr(m0_pb))
rf_pb
icc_rf_pb <- rf_pb[1,4]/(rf_pb[1,4]+rf_pb[2,4]) 
icc_rf_pb # 60% attributed to between person effect

## MODEL 1a: SA+RA+TB->PB

### Random intercept vs. random slope
m1_pb_ri <- lmer(formula = PB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                   SA_mean_c * SA_c + 
                   RA_mean_c * RA_c + 
                   TB_mean_c * TB_c + 
                   (1 | ID), 
                 data=data_h1,
                 na.action=na.exclude)

m1_pb_ris <- lmer(formula = PB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                    SA_mean_c * SA_c + 
                    RA_mean_c * RA_c + 
                    TB_mean_c * TB_c + 
                    (1 + SA_c + RA_c + TB_c | ID), 
                  data=data_h1,
                  na.action=na.exclude)

anova(m1_pb_ri,m1_pb_ris)
summary(m1_pb_ris)

### Quasi-R2; REML should be switched to ML
m0_pb_ml <- lmer(formula = PB ~ 1 + (1|ID), 
               data=data_h1,
               REML=FALSE,
               na.action=na.exclude)
m1_pb_ris_ml <- lmer(formula = PB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                    SA_mean_c * SA_c + 
                    RA_mean_c * RA_c + 
                    TB_mean_c * TB_c + 
                    (1 + SA_c + RA_c + TB_c | ID), 
                  data=data_h1,
                  REML=FALSE,
                  na.action=na.exclude)

quasi_r2 <- 1-(var(residuals(m1_pb_ris_ml),na.rm=TRUE)/var(residuals(m0_pb_ml),na.rm=TRUE)) 
quasi_r2 #50%

## MODEL 1b: SA+RA+TB+PB(n-1)+TB(n-1)->PB

### Random intercept vs. random slope
m2_pb_ri <- lmer(formula = PB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                   SA_mean_c * SA_c + 
                   RA_mean_c * RA_c + 
                   TB_mean_c * TB_c +
                   PB_lag_c + 
                   TB_lag_c + 
                   (1 | ID), 
                 data=data_h1,
                 na.action=na.exclude)

m2_pb_ris <- lmer(formula = PB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                    SA_mean_c * SA_c + 
                    RA_mean_c * RA_c + 
                    TB_mean_c * TB_c +
                    PB_lag_c + 
                    TB_lag_c + 
                    (1 + SA_c + RA_c + TB_c + PB_lag_c + TB_lag_c | ID), 
                  data=data_h1,
                  na.action=na.exclude)

anova(m2_pb_ri,m2_pb_ris)
summary(m2_pb_ris)

### Quasi-R2; REML should be switched to ML
m0_pb_ml <- lmer(formula = PB ~ 1 + (1|ID), 
                 data=data_h1,
                 REML=FALSE,
                 na.action=na.exclude)
m2_pb_ris_ml <- lmer(formula = PB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                       SA_mean_c * SA_c + 
                       RA_mean_c * RA_c + 
                       TB_mean_c * TB_c +
                       PB_lag_c + 
                       TB_lag_c + 
                       (1 + SA_c + RA_c + TB_c + PB_lag_c + TB_lag_c | ID), 
                     data=data_h1,
                     REML=FALSE,
                     na.action=na.exclude)

quasi_r2 <- 1-(var(residuals(m2_pb_ris_ml),na.rm=TRUE)/var(residuals(m0_pb_ml),na.rm=TRUE)) 
quasi_r2 #55%

## MODEL 1c: SA(n-1)+RA(n-1)+TB(n-1)->PB

### Random intercept vs. random slope
m3_pb_ri <- lmer(formula = PB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                   SA_mean_c * SA_lag_c + 
                   RA_mean_c * RA_lag_c + 
                   TB_mean_c * TB_lag_c + 
                   (1 | ID), 
                 data=data_h1,
                 na.action=na.exclude)

m3_pb_ris <- lmer(formula = PB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                    SA_mean_c * SA_lag_c + 
                    RA_mean_c * RA_lag_c + 
                    TB_mean_c * TB_lag_c + 
                    (1 + SA_lag_c + RA_lag_c + TB_lag_c | ID), 
                  data=data_h1,
                  na.action=na.exclude)

anova(m3_pb_ri,m3_pb_ris)
summary(m3_pb_ris)

### Quasi-R2; REML should be switched to ML
m0_pb_ml <- lmer(formula = PB ~ 1 + (1|ID), 
                 data=data_h1,
                 REML=FALSE,
                 na.action=na.exclude)
m3_pb_ris_ml <- lmer(formula = PB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                       SA_mean_c * SA_lag_c + 
                       RA_mean_c * RA_lag_c + 
                       TB_mean_c * TB_lag_c + 
                       (1 + SA_lag_c + RA_lag_c + TB_lag_c | ID), 
                     data=data_h1,
                     REML=FALSE,
                     na.action=na.exclude)

quasi_r2 <- 1-(var(residuals(m3_pb_ris_ml),na.rm=TRUE)/var(residuals(m0_pb_ml),na.rm=TRUE)) 
quasi_r2 #15%

## MODEL 1d: SA(n-1)+RA(n-1)+PB(n-1)+TB(n-1)->PB

### Random intercept vs. random slope
m4_pb_ri <- lmer(formula = PB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                   SA_mean_c * SA_lag_c + 
                   RA_mean_c * RA_lag_c + 
                   TB_mean_c * TB_lag_c + 
                   PB_lag_c +
                   (1 | ID), 
                 data=data_h1,
                 na.action=na.exclude)

m4_pb_ris <- lmer(formula = PB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                    SA_mean_c * SA_lag_c + 
                    RA_mean_c * RA_lag_c + 
                    TB_mean_c * TB_lag_c + 
                    PB_lag_c + 
                    (1 + SA_lag_c + RA_lag_c + PB_lag_c + TB_lag_c | ID), 
                  data=data_h1,
                  na.action=na.exclude)

anova(m4_pb_ri,m4_pb_ris)
summary(m4_pb_ris)

### Quasi-R2; REML should be switched to ML
m0_pb_ml <- lmer(formula = PB ~ 1 + (1|ID), 
                 data=data_h1,
                 REML=FALSE,
                 na.action=na.exclude)
m4_pb_ris_ml <- lmer(formula = PB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                       SA_mean_c * SA_lag_c + 
                       RA_mean_c * RA_lag_c + 
                       TB_mean_c * TB_lag_c + 
                       PB_lag_c + 
                       (1 + SA_lag_c + RA_lag_c + PB_lag_c + TB_lag_c | ID), 
                     data=data_h1,
                     REML=FALSE,
                     na.action=na.exclude)

quasi_r2 <- 1-(var(residuals(m4_pb_ris_ml),na.rm=TRUE)/var(residuals(m0_pb_ml),na.rm=TRUE)) 
quasi_r2 #19%


# MODEL 2: SA/RA/PB ->TB
## MODEL NULL 
m_tb_0 <- lmer(formula = TB ~ 1 + (1|ID), 
               data=data_h1,
               na.action=na.exclude)
summary(m_tb_0)
rf_tb <- as.data.frame(VarCorr(m_tb_0))
rf_tb
icc_rf_tb <- rf_tb[1,4]/(rf_tb[1,4]+rf_tb[2,4]) 
icc_rf_tb # 58% attributed to between person effect

## MODEL 2a: SA+RA+PB->TB

### Random intercept vs. random slope
m1_tb_ri <- lmer(formula = TB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                   SA_mean_c * SA_c + 
                   RA_mean_c * RA_c + 
                   PB_mean_c * PB_c + 
                   (1 | ID), 
                 data=data_h1,
                 na.action=na.exclude)

m1_tb_ris <- lmer(formula = TB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                    SA_mean_c * SA_c + 
                    RA_mean_c * RA_c + 
                    PB_mean_c * PB_c + 
                    (1 + SA_c + RA_c + PB_c | ID), 
                  data=data_h1,
                  na.action=na.exclude)

anova(m1_tb_ri,m1_tb_ris)
summary(m1_tb_ris)

### Quasi-R2; REML should be switched to ML
m0_tb_ml <- lmer(formula = TB ~ 1 + (1|ID), 
                 data=data_h1,
                 REML=FALSE,
                 na.action=na.exclude)
m1_tb_ris_ml <- lmer(formula = TB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                       SA_mean_c * SA_c + 
                       RA_mean_c * RA_c + 
                       PB_mean_c * PB_c + 
                       (1 + SA_c + RA_c + PB_c | ID), 
                     data=data_h1,
                     REML=FALSE,
                     na.action=na.exclude)

quasi_r2 <- 1-(var(residuals(m1_tb_ris_ml),na.rm=TRUE)/var(residuals(m0_tb_ml),na.rm=TRUE)) 
quasi_r2 #47%

## MODEL 2b: SA+RA+PB+PB(n-1)+TB(n-1)->TB

### Random intercept vs. random slope
m2_tb_ri <- lmer(formula = TB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                   SA_mean_c * SA_c + 
                   RA_mean_c * RA_c + 
                   PB_mean_c * PB_c +
                   PB_lag_c + 
                   TB_lag_c + 
                   (1 | ID), 
                 data=data_h1,
                 na.action=na.exclude)

m2_tb_ris <- lmer(formula = TB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                    SA_mean_c * SA_c + 
                    RA_mean_c * RA_c + 
                    PB_mean_c * PB_c +
                    PB_lag_c + 
                    TB_lag_c + 
                    (1 + SA_c + RA_c + PB_c + PB_lag_c + TB_lag_c | ID), 
                  data=data_h1,
                  na.action=na.exclude)

anova(m2_tb_ri,m2_tb_ris)
summary(m2_tb_ris)

### Quasi-R2; REML should be switched to ML
m0_tb_ml <- lmer(formula = TB ~ 1 + (1|ID), 
                 data=data_h1,
                 REML=FALSE,
                 na.action=na.exclude)
m2_tb_ris_ml <- lmer(formula = TB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                       SA_mean_c * SA_c + 
                       RA_mean_c * RA_c + 
                       PB_mean_c * PB_c +
                       PB_lag_c + 
                       TB_lag_c + 
                       (1 + SA_c + RA_c + PB_c + PB_lag_c + TB_lag_c | ID), 
                     data=data_h1,
                     REML=FALSE,
                     na.action=na.exclude)

quasi_r2 <- 1-(var(residuals(m2_tb_ris_ml),na.rm=TRUE)/var(residuals(m0_tb_ml),na.rm=TRUE)) 
quasi_r2 #51%

## MODEL 2c: SA(n-1)+RA(n-1)+PB(n-1)->TB

### Random intercept vs. random slope
m3_tb_ri <- lmer(formula = TB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                   SA_mean_c * SA_lag_c + 
                   RA_mean_c * RA_lag_c + 
                   PB_mean_c * PB_lag_c + 
                   (1 | ID), 
                 data=data_h1,
                 na.action=na.exclude)

m3_tb_ris <- lmer(formula = TB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                    SA_mean_c * SA_lag_c + 
                    RA_mean_c * RA_lag_c + 
                    PB_mean_c * PB_lag_c + 
                    (1 + SA_lag_c + RA_lag_c + PB_lag_c | ID), 
                  data=data_h1,
                  na.action=na.exclude)

anova(m3_tb_ri,m3_tb_ris)
summary(m3_tb_ris)

### Quasi-R2; REML should be switched to ML
m0_tb_ml <- lmer(formula = TB ~ 1 + (1|ID), 
                 data=data_h1,
                 REML=FALSE,
                 na.action=na.exclude)
m3_tb_ris_ml <- lmer(formula = TB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                       SA_mean_c * SA_lag_c + 
                       RA_mean_c * RA_lag_c + 
                       PB_mean_c * PB_lag_c + 
                       (1 + SA_lag_c + RA_lag_c + PB_lag_c | ID), 
                     data=data_h1,
                     REML=FALSE,
                     na.action=na.exclude)

quasi_r2 <- 1-(var(residuals(m3_tb_ris_ml),na.rm=TRUE)/var(residuals(m0_tb_ml),na.rm=TRUE)) 
quasi_r2 #14%

## MODEL 1d: SA(n-1)+RA(n-1)+PB(n-1)+TB(n-1)->TB

### Random intercept vs. random slope
m4_tb_ri <- lmer(formula = TB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                   SA_mean_c * SA_lag_c + 
                   RA_mean_c * RA_lag_c + 
                   PB_mean_c * PB_lag_c + 
                   TB_lag_c +
                   (1 | ID), 
                 data=data_h1,
                 na.action=na.exclude)

m4_tb_ris <- lmer(formula = TB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                    SA_mean_c * SA_lag_c + 
                    RA_mean_c * RA_lag_c + 
                    PB_mean_c * PB_lag_c + 
                    TB_lag_c + 
                    (1 + SA_lag_c + RA_lag_c + PB_lag_c + TB_lag_c | ID), 
                  data=data_h1,
                  na.action=na.exclude)

anova(m4_tb_ri,m4_tb_ris)
summary(m4_tb_ris)

### Quasi-R2; REML should be switched to ML
m0_tb_ml <- lmer(formula = TB ~ 1 + (1|ID), 
                 data=data_h1,
                 REML=FALSE,
                 na.action=na.exclude)
m4_tb_ris_ml <- lmer(formula = TB ~ 1 + Prompt_Num + First_Prompt_of_Day +
                       SA_mean_c * SA_lag_c + 
                       RA_mean_c * RA_lag_c + 
                       PB_mean_c * PB_lag_c + 
                       TB_lag_c + 
                       (1 + SA_lag_c + RA_lag_c + PB_lag_c + TB_lag_c | ID), 
                     data=data_h1,
                     REML=FALSE,
                     na.action=na.exclude)

quasi_r2 <- 1-(var(residuals(m4_tb_ris_ml),na.rm=TRUE)/var(residuals(m0_tb_ml),na.rm=TRUE)) 
quasi_r2 #15%
